### ISSUE TITLE
Recommendation: Accounting user permission

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#194] opened 2021-09-24 22:28 UTC
While the accounting user have no access to entire menu while on dashboard.php the full menu shows if accounting will click on the clients

![image](https://user-images.githubusercontent.com/38830718/134745266-8dc15462-cff0-41bc-aa70-56928a95fbbd.png)

After selecting a client from clients.php, the full menu with sensitive data that the accounting users shouldn't have access to

![image](https://user-images.githubusercontent.com/38830718/134745365-bdf9fabc-5d75-430f-ae48-10e27bc7d94b.png)

can we have the accounting user strictly dealing with invoices only, so he will not see any other not-related items
like hide the assets and support menu

Maybe in user settings, option to select which menu should have access to

Thank you!

**Comment by johnnyq** [comment] 2021-10-04 13:46
@aftechro Good call I must of missed this I will get this fixed up

**Comment by wrongecho** [comment] 2022-02-27 09:38
This is actually a duplicate of #321. This was raised first but #321 has more discussion so will close against that.

**Closed by wrongecho** 2022-02-27 09:38 UTC
Labels: bug
